# Generated by Django 5.1.6 on 2026-03-09 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_notification'),
        ('learning', '0011_user_avatar_user_bio_alter_aiagent_systeminstruction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('lesson_view', 'طالب شاهد الدرس'), ('test_attempt', 'طالب حل الاختبار'), ('lesson_publish', 'درس جديد منشور'), ('test_publish', 'اختبار جديد منشور'), ('schedule_update', 'تحديث جدول المهام')], db_column='NotifType', max_length=20),
        ),
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('lesson', 'حصة'), ('exam', 'اختبار')], db_column='EntryType', max_length=10)),
                ('entry_date', models.DateField(db_column='EntryDate')),
                ('start_time', models.TimeField(db_column='StartTime')),
                ('end_time', models.TimeField(db_column='EndTime')),
                ('notes', models.CharField(blank=True, db_column='Notes', default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdatedAt')),
                ('class_obj', models.ForeignKey(db_column='ClassID', on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='learning.class')),
                ('subject', models.ForeignKey(db_column='SubjectID', on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='learning.subject')),
                ('teacher', models.ForeignKey(db_column='TeacherID', on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='learning.teacher')),
            ],
            options={
                'db_table': 'ScheduleEntry',
                'ordering': ['entry_date', 'start_time'],
                'indexes': [models.Index(fields=['class_obj', 'entry_date'], name='idx_schedule_class_date'), models.Index(fields=['teacher', 'entry_date'], name='idx_schedule_teacher_date')],
            },
        ),
    ]
