# Generated by Django 5.1.6 on 2026-03-10 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_notification_notif_type_scheduleentry'),
        ('learning', '0011_user_avatar_user_bio_alter_aiagent_systeminstruction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('lesson_view', 'طالب شاهد الدرس'), ('test_attempt', 'طالب حل الاختبار'), ('lesson_publish', 'درس جديد منشور'), ('test_publish', 'اختبار جديد منشور'), ('schedule_update', 'تحديث جدول المهام'), ('grade_update', 'تحديث درجة')], db_column='NotifType', max_length=20),
        ),
        migrations.CreateModel(
            name='ActivityGrade',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_name', models.CharField(db_column='ActivityName', max_length=200)),
                ('max_score', models.DecimalField(db_column='MaxScore', decimal_places=2, max_digits=6)),
                ('student_score', models.DecimalField(db_column='StudentScore', decimal_places=2, max_digits=6)),
                ('teacher_note', models.TextField(blank=True, db_column='TeacherNote', default='')),
                ('visible_to', models.CharField(choices=[('student', 'الطالب فقط'), ('parent', 'الأهل فقط'), ('student_parent', 'الطالب والأهل')], db_column='VisibleTo', default='student_parent', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdatedAt')),
                ('student', models.ForeignKey(db_column='StudentID', on_delete=django.db.models.deletion.CASCADE, related_name='activity_grades', to='learning.student')),
                ('subject', models.ForeignKey(db_column='SubjectID', on_delete=django.db.models.deletion.CASCADE, related_name='activity_grades', to='learning.subject')),
                ('teacher', models.ForeignKey(db_column='TeacherID', on_delete=django.db.models.deletion.CASCADE, related_name='activity_grades', to='learning.teacher')),
            ],
            options={
                'db_table': 'ActivityGrade',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['teacher', 'student', '-created_at'], name='idx_ag_teacher_student'), models.Index(fields=['subject', '-created_at'], name='idx_ag_subject_date')],
            },
        ),
        migrations.CreateModel(
            name='GradeOverride',
            fields=[
                ('override_id', models.AutoField(primary_key=True, serialize=False)),
                ('adjusted_score', models.DecimalField(db_column='AdjustedScore', decimal_places=2, max_digits=6)),
                ('reason', models.TextField(db_column='Reason')),
                ('teacher_note', models.TextField(blank=True, db_column='TeacherNote', default='')),
                ('visible_to', models.CharField(choices=[('student', 'الطالب فقط'), ('parent', 'الأهل فقط'), ('student_parent', 'الطالب والأهل')], db_column='VisibleTo', default='student_parent', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdatedAt')),
                ('attempt', models.OneToOneField(db_column='AttemptID', on_delete=django.db.models.deletion.CASCADE, related_name='grade_override', to='learning.testattempt')),
                ('teacher', models.ForeignKey(db_column='TeacherID', on_delete=django.db.models.deletion.CASCADE, related_name='grade_overrides', to='learning.teacher')),
            ],
            options={
                'db_table': 'GradeOverride',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['teacher', '-created_at'], name='idx_go_teacher_date')],
            },
        ),
    ]
