# Generated by Django 5.1.6 on 2026-03-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_notification_notif_type_activitygrade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('lesson_view', 'طالب شاهد الدرس'), ('test_attempt', 'طالب حل الاختبار'), ('lesson_publish', 'درس جديد منشور'), ('test_publish', 'اختبار جديد منشور'), ('schedule_update', 'تحديث جدول المهام'), ('grade_update', 'تحديث درجة'), ('parent_grade', 'رصد درجة الطالب'), ('parent_note', 'ملاحظة من المعلم'), ('parent_attention', 'تنبيه تشتت الانتباه'), ('parent_lesson', 'درس جديد للطالب'), ('parent_test', 'اختبار جديد للطالب')], db_column='NotifType', max_length=20),
        ),
    ]
