# Generated by Django 5.1.6 on 2026-03-19 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_schedule_online_link'),
        ('accounts', '0005_alter_notification_notif_type'),
    ]

    operations = [
    ]
