# Generated by Django 5.1.6 on 2026-03-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_merge_20260319_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleentry',
            name='online_link',
            field=models.URLField(blank=True, db_column='OnlineLink', default='', max_length=500),
        ),
    ]
