# Generated by Django 5.1.6 on 2026-03-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_scheduleentry_online_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleentry',
            name='online_link',
            field=models.URLField(blank=True, db_column='OnlineLink', max_length=500, null=True),
        ),
    ]
