# Generated by Django 6.0.2 on 2026-02-09 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiAgent',
            fields=[
                ('agentid', models.AutoField(db_column='AgentID', primary_key=True, serialize=False)),
                ('agentname', models.CharField(db_column='AgentName', max_length=50)),
                ('agenttype', models.CharField(db_column='AgentType', max_length=50)),
                ('api_key', models.TextField(db_column='API_Key')),
                ('version', models.CharField(db_column='Version', max_length=50)),
                ('systeminstruction', models.TextField(db_column='SystemInstruction')),
                ('isactive', models.BooleanField(db_column='IsActive', default=True)),
            ],
            options={
                'db_table': 'AI_Agent',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('classid', models.AutoField(db_column='ClassID', primary_key=True, serialize=False)),
                ('classname', models.CharField(db_column='ClassName', max_length=50)),
            ],
            options={
                'db_table': 'Class',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Learningsession',
            fields=[
                ('sessionid', models.AutoField(db_column='SessionID', primary_key=True, serialize=False)),
                ('starttime', models.DateTimeField(auto_now_add=True, db_column='StartTime')),
                ('endtime', models.DateTimeField(blank=True, db_column='EndTime', null=True)),
                ('sessionstatus', models.CharField(db_column='SessionStatus', default='Active', max_length=20)),
                ('duration', models.DurationField(blank=True, db_column='Duration', null=True)),
                ('avgfocusscore', models.DecimalField(blank=True, db_column='AvgFocusScore', decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'LearningSession',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('userid', models.AutoField(db_column='UserID', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='Username', max_length=50, unique=True)),
                ('fullname', models.CharField(db_column='FullName', max_length=100)),
                ('email', models.EmailField(db_column='Email', max_length=100)),
                ('userrole', models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Student', 'Student'), ('Teacher', 'Teacher'), ('Parent', 'Parent')], db_column='UserRole', max_length=50, null=True)),
                ('identitynumber', models.BigIntegerField(blank=True, db_column='IdentityNumber', null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'User',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Attentionlog',
            fields=[
                ('logid', models.AutoField(db_column='LogID', primary_key=True, serialize=False)),
                ('logtime', models.DateTimeField(auto_now_add=True, db_column='LogTime')),
                ('focuspercentage', models.DecimalField(db_column='FocusPercentage', decimal_places=2, max_digits=5)),
                ('isdistracted', models.BooleanField(db_column='IsDistracted')),
                ('actiontaken', models.CharField(blank=True, db_column='ActionTaken', max_length=100, null=True)),
                ('sessionid', models.ForeignKey(db_column='SessionID', on_delete=django.db.models.deletion.CASCADE, to='learning.learningsession')),
            ],
            options={
                'db_table': 'AttentionLog',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AiInteraction',
            fields=[
                ('interactionid', models.AutoField(db_column='InteractionID', primary_key=True, serialize=False)),
                ('childquery', models.TextField(db_column='ChildQuery')),
                ('ai_response', models.TextField(db_column='AI_Response')),
                ('interactiontime', models.DateTimeField(auto_now_add=True, db_column='InteractionTime')),
                ('sessionid', models.ForeignKey(db_column='SessionID', on_delete=django.db.models.deletion.CASCADE, to='learning.learningsession')),
            ],
            options={
                'db_table': 'AI_Interaction',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lessoncontent',
            fields=[
                ('lessonid', models.AutoField(db_column='LessonID', primary_key=True, serialize=False)),
                ('originaltext', models.TextField(db_column='OriginalText')),
                ('ai_visualpath', models.CharField(blank=True, db_column='AI_VisualPath', max_length=500, null=True)),
                ('ai_audiopath', models.CharField(blank=True, db_column='AI_AudioPath', max_length=500, null=True)),
                ('ai_generatedtext', models.TextField(blank=True, db_column='AI_GeneratedText', null=True)),
                ('complexitylevel', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], db_column='ComplexityLevel', default='Easy', max_length=10)),
                ('createdat', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Published', 'Published')], db_column='Status', default='Pending', max_length=10)),
                ('agentid', models.ForeignKey(blank=True, db_column='AgentID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.aiagent')),
            ],
            options={
                'db_table': 'LessonContent',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='learningsession',
            name='lessonid',
            field=models.ForeignKey(db_column='LessonID', on_delete=django.db.models.deletion.CASCADE, to='learning.lessoncontent'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentid', models.AutoField(db_column='StudentID', primary_key=True, serialize=False)),
                ('age', models.IntegerField(db_column='Age')),
                ('currentfocuslevel', models.FloatField(blank=True, db_column='CurrentFocusLevel', null=True)),
                ('classid', models.ForeignKey(blank=True, db_column='ClassID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.class')),
                ('userid', models.OneToOneField(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Student',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Performancereport',
            fields=[
                ('reportid', models.AutoField(db_column='ReportID', primary_key=True, serialize=False)),
                ('avgattentionscore', models.FloatField(db_column='AvgAttentionScore')),
                ('testscore', models.IntegerField(db_column='TestScore')),
                ('totaltimespent', models.IntegerField(db_column='TotalTimeSpent')),
                ('teachercomments', models.TextField(blank=True, db_column='TeacherComments', null=True)),
                ('reportdate', models.DateTimeField(auto_now_add=True, db_column='ReportDate')),
                ('lessonid', models.ForeignKey(db_column='LessonID', on_delete=django.db.models.deletion.CASCADE, to='learning.lessoncontent')),
                ('studentid', models.ForeignKey(db_column='StudentID', on_delete=django.db.models.deletion.CASCADE, to='learning.student')),
            ],
            options={
                'db_table': 'PerformanceReport',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('parentid', models.AutoField(db_column='ParentID', primary_key=True, serialize=False)),
                ('userid', models.OneToOneField(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('childid', models.ForeignKey(blank=True, db_column='ChildID', null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.student')),
            ],
            options={
                'db_table': 'Parent',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='learningsession',
            name='studentid',
            field=models.ForeignKey(db_column='StudentID', on_delete=django.db.models.deletion.CASCADE, to='learning.student'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subjectid', models.AutoField(db_column='SubjectID', primary_key=True, serialize=False)),
                ('subjectname', models.CharField(db_column='SubjectName', max_length=50)),
                ('classid', models.ForeignKey(blank=True, db_column='ClassID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.class')),
            ],
            options={
                'db_table': 'Subject',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='lessoncontent',
            name='subjectid',
            field=models.ForeignKey(db_column='SubjectID', on_delete=django.db.models.deletion.CASCADE, to='learning.subject'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacherid', models.AutoField(db_column='TeacherID', primary_key=True, serialize=False)),
                ('specialization', models.CharField(db_column='Specialization', max_length=50)),
                ('userid', models.OneToOneField(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Teacher',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='teacherid',
            field=models.ForeignKey(db_column='TeacherID', on_delete=django.db.models.deletion.CASCADE, to='learning.teacher'),
        ),
        migrations.AddField(
            model_name='lessoncontent',
            name='teacherid',
            field=models.ForeignKey(db_column='TeacherID', on_delete=django.db.models.deletion.CASCADE, to='learning.teacher'),
        ),
        migrations.AddField(
            model_name='class',
            name='teacherid',
            field=models.ForeignKey(db_column='TeacherID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.teacher'),
        ),
        migrations.AddField(
            model_name='aiagent',
            name='teacherid',
            field=models.ForeignKey(blank=True, db_column='TeacherID', null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.teacher'),
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('testid', models.AutoField(db_column='TestID', primary_key=True, serialize=False)),
                ('testtitle', models.CharField(db_column='TestTitle', max_length=100)),
                ('totalquestions', models.IntegerField(db_column='TotalQuestions')),
                ('durationtaken', models.IntegerField(blank=True, db_column='DurationTaken', null=True)),
                ('lessonid', models.ForeignKey(db_column='LessonID', on_delete=django.db.models.deletion.CASCADE, to='learning.lessoncontent')),
                ('teacherid', models.ForeignKey(db_column='TeacherID', on_delete=django.db.models.deletion.CASCADE, to='learning.teacher')),
            ],
            options={
                'db_table': 'Test',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('questionid', models.AutoField(db_column='QuestionID', primary_key=True, serialize=False)),
                ('questiontext', models.CharField(db_column='QuestionText', max_length=150)),
                ('optiona', models.CharField(db_column='OptionA', max_length=50)),
                ('optionb', models.CharField(db_column='OptionB', max_length=50)),
                ('optionc', models.CharField(blank=True, db_column='OptionC', max_length=50, null=True)),
                ('optiond', models.CharField(blank=True, db_column='OptionD', max_length=50, null=True)),
                ('correctanswer', models.CharField(db_column='CorrectAnswer', max_length=50)),
                ('points', models.IntegerField(db_column='Points')),
                ('testid', models.ForeignKey(db_column='TestID', on_delete=django.db.models.deletion.CASCADE, to='learning.test')),
            ],
            options={
                'db_table': 'Question',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Testattempt',
            fields=[
                ('attemptid', models.AutoField(db_column='AttemptID', primary_key=True, serialize=False)),
                ('score', models.IntegerField(db_column='Score')),
                ('teacherfeedback', models.TextField(blank=True, db_column='TeacherFeedback', null=True)),
                ('attemptdate', models.DateTimeField(auto_now_add=True, db_column='AttemptDate')),
                ('durationtaken', models.IntegerField(blank=True, db_column='DurationTaken', null=True)),
                ('studentid', models.ForeignKey(db_column='StudentID', on_delete=django.db.models.deletion.CASCADE, to='learning.student')),
                ('testid', models.ForeignKey(db_column='TestID', on_delete=django.db.models.deletion.CASCADE, to='learning.test')),
            ],
            options={
                'db_table': 'TestAttempt',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Studentanswer',
            fields=[
                ('answerid', models.AutoField(db_column='AnswerID', primary_key=True, serialize=False)),
                ('selectedoption', models.CharField(db_column='SelectedOption', max_length=50)),
                ('iscorrect', models.BooleanField(db_column='IsCorrect')),
                ('responsetimeseconds', models.IntegerField(blank=True, db_column='ResponseTimeSeconds', null=True)),
                ('questionid', models.ForeignKey(db_column='QuestionID', on_delete=django.db.models.deletion.CASCADE, to='learning.question')),
                ('attemptid', models.ForeignKey(db_column='AttemptID', on_delete=django.db.models.deletion.CASCADE, to='learning.testattempt')),
            ],
            options={
                'db_table': 'StudentAnswer',
                'managed': True,
            },
        ),
    ]
