# Generated by Django 6.0.2 on 2026-02-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessoncontent',
            name='lessontitle',
            field=models.CharField(db_column='LessonTitle', default='عنوان الدرس الجديد', max_length=200),
        ),
        migrations.AlterField(
            model_name='aiagent',
            name='agenttype',
            field=models.CharField(db_column='AgentType', default='Gemini', max_length=50),
        ),
        migrations.AlterField(
            model_name='aiagent',
            name='api_key',
            field=models.TextField(blank=True, db_column='API_Key', null=True),
        ),
        migrations.AlterField(
            model_name='aiagent',
            name='systeminstruction',
            field=models.TextField(db_column='SystemInstruction', help_text='التعليمات التي يتبعها AI لتبسيط الدرس'),
        ),
        migrations.AlterField(
            model_name='aiagent',
            name='version',
            field=models.CharField(db_column='Version', default='1.5-flash', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='userrole',
            field=models.CharField(blank=True, choices=[('', 'نوع المستخدم'), ('Admin', 'مشرف'), ('Student', 'طالب'), ('Teacher', 'معلم'), ('Parent', 'ولي الأمر')], db_column='UserRole', max_length=50, null=True),
        ),
    ]
