# Generated by Django 6.0.2 on 2026-02-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_lessoncontent_lessontitle_alter_aiagent_agenttype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='assigned_classes',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='learning.class'),
        ),
    ]
