# Generated by Django 6.0.2 on 2026-02-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_teacher_assigned_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessoncontent',
            name='ai_audiopath',
            field=models.TextField(blank=True, db_column='AI_AudioPath', null=True),
        ),
        migrations.AlterField(
            model_name='lessoncontent',
            name='ai_visualpath',
            field=models.TextField(blank=True, db_column='AI_VisualPath', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userrole',
            field=models.CharField(blank=True, choices=[('', 'نوع المستخدم'), ('Admin', 'مشرف'), ('Student', 'طالب'), ('Teacher', 'معلم'), ('Parent', 'ولي أمر')], db_column='UserRole', max_length=50, null=True),
        ),
    ]
