# Generated by Django 5.1.6 on 2026-02-14 19:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_alter_lessoncontent_ai_audiopath_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessoncontent',
            name='ai_videopath',
            field=models.TextField(blank=True, db_column='AI_VideoPath', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='chat_api_key',
            field=models.CharField(blank=True, db_column='Chat_API_Key', help_text='اختياري: مفتاح الطالب الخاص', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='chats_today',
            field=models.IntegerField(db_column='ChatsToday', default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='daily_chat_limit',
            field=models.IntegerField(db_column='DailyChatLimit', default=20),
        ),
        migrations.AddField(
            model_name='student',
            name='last_chat_reset',
            field=models.DateField(db_column='LastChatReset', default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='teacher',
            name='daily_lesson_limit',
            field=models.IntegerField(db_column='DailyLessonLimit', default=10),
        ),
        migrations.AddField(
            model_name='teacher',
            name='daily_video_limit',
            field=models.IntegerField(db_column='DailyVideoLimit', default=2),
        ),
        migrations.AddField(
            model_name='teacher',
            name='gemini_api_key',
            field=models.CharField(blank=True, db_column='Gemini_API_Key', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='last_reset_date',
            field=models.DateField(db_column='LastResetDate', default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='teacher',
            name='lessons_today',
            field=models.IntegerField(db_column='LessonsToday', default=0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='videos_today',
            field=models.IntegerField(db_column='VideosToday', default=0),
        ),
    ]
