# Generated by Django 5.1.6 on 2026-02-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_lessoncontent_ai_videopath_student_chat_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessoncontent',
            name='ai_visualpath',
            field=models.JSONField(blank=True, db_column='AI_VisualPath', null=True),
        ),
    ]
