# Generated by Django 5.1.6 on 2026-02-14 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_alter_lessoncontent_ai_visualpath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessoncontent',
            name='ai_visualpath',
            field=models.JSONField(blank=True, db_column='AI_VisualPath', default=list, null=True),
        ),
    ]
