# Generated by Django 5.1.6 on 2026-02-14 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_alter_lessoncontent_ai_visualpath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userrole',
            field=models.CharField(blank=True, choices=[('', 'نوع المستخدم'), ('Admin', 'مشرف'), ('Student', 'طالب'), ('Teacher', 'معلم'), ('Parent', 'ولي أمر')], db_column='UserRole', default='Admin', max_length=50, null=True),
        ),
    ]
