# Generated by Django 5.1.6 on 2026-02-14 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_alter_user_userrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='identitynumber',
            field=models.BigIntegerField(blank=True, db_column='IdentityNumber', db_index=True, null=True, unique=True),
        ),
    ]
