# Generated by Django 6.0.2 on 2026-03-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('learning', '0009_alter_user_identitynumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userrole',
            field=models.CharField(blank=True, choices=[('', 'نوع المستخدم'), ('Admin', 'مشرف'), ('Student', 'طالب'), ('Teacher', 'معلم'), ('Parent', 'ولي أمر')], db_column='UserRole', max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='lessoncontent',
            index=models.Index(fields=['teacherid', '-createdat'], name='idx_lesson_teacher_date'),
        ),
        migrations.AddIndex(
            model_name='lessoncontent',
            index=models.Index(fields=['subjectid'], name='idx_lesson_subjectid'),
        ),
        migrations.AddIndex(
            model_name='lessoncontent',
            index=models.Index(fields=['status'], name='idx_lesson_status'),
        ),
        migrations.AddIndex(
            model_name='performancereport',
            index=models.Index(fields=['studentid', '-reportdate'], name='idx_report_student_date'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['userrole'], name='idx_user_role'),
        ),
    ]
