# Generated by Django 5.1.6 on 2026-03-07 15:18

import django.core.validators
import learning.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_alter_user_userrole_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='صورة شخصية (JPG/PNG/WebP — بحد أقصى 2MB)', null=True, upload_to=learning.models._avatar_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, default='', help_text='نبذة مختصرة عن المستخدم', max_length=300),
        ),
        migrations.AlterField(
            model_name='aiagent',
            name='systeminstruction',
            field=models.TextField(db_column='SystemInstruction'),
        ),
        migrations.AlterField(
            model_name='student',
            name='chat_api_key',
            field=models.CharField(blank=True, db_column='Chat_API_Key', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='identitynumber',
            field=models.BigIntegerField(blank=True, db_column='IdentityNumber', null=True, unique=True),
        ),
    ]
