# Generated by Django 5.1.6 on 2026-03-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0014_teacher_directorate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='chat_api_key',
            field=models.CharField(blank=True, db_column='Chat_API_Key', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='directorate',
            field=models.CharField(blank=True, db_column='Directorate', default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='gemini_api_key',
            field=models.CharField(blank=True, db_column='Gemini_API_Key', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='specialization',
            field=models.CharField(db_column='Specialization', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_column='Email', max_length=100),
        ),
    ]
