# Generated by Django 5.1.6 on 2026-03-17 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0019_fix_academic_year_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='academic_year',
        ),
    ]
