# Generated by Django 5.1.6 on 2026-03-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0020_remove_class_academic_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correctanswer',
            field=models.CharField(db_column='CorrectAnswer', max_length=300),
        ),
        migrations.AlterField(
            model_name='question',
            name='optiona',
            field=models.CharField(db_column='OptionA', max_length=300),
        ),
        migrations.AlterField(
            model_name='question',
            name='optionb',
            field=models.CharField(db_column='OptionB', max_length=300),
        ),
        migrations.AlterField(
            model_name='question',
            name='optionc',
            field=models.CharField(blank=True, db_column='OptionC', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='optiond',
            field=models.CharField(blank=True, db_column='OptionD', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='questiontext',
            field=models.CharField(db_column='QuestionText', max_length=400),
        ),
    ]
