# Generated by Django 5.1.6 on 2026-03-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0021_alter_question_correctanswer_alter_question_optiona_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessoncontent',
            name='difficulty_level',
            field=models.CharField(blank=True, choices=[('simple', 'بسيط'), ('medium', 'متوسط'), ('advanced', 'عميق')], db_column='DifficultyLevel', default='simple', max_length=20),
        ),
        migrations.AddField(
            model_name='lessoncontent',
            name='learning_style',
            field=models.CharField(blank=True, db_column='LearningStyle', default='storytelling', max_length=30),
        ),
        migrations.AddField(
            model_name='lessoncontent',
            name='para_img_mapping',
            field=models.JSONField(blank=True, db_column='ParaImgMapping', default=dict),
        ),
        migrations.AddField(
            model_name='lessoncontent',
            name='target_age_group',
            field=models.IntegerField(blank=True, db_column='TargetAgeGroup', null=True),
        ),
    ]
