# Generated by Django 5.1.6 on 2026-03-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0023_studentanswer_selectedoption_300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentanswer',
            name='selectedoption',
            field=models.CharField(db_column='SelectedOption', max_length=50),
        ),
    ]
