# Generated by Django 5.1.6 on 2026-04-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0024_alter_studentanswer_selectedoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessoncontent',
            name='simplified_content',
            field=models.TextField(blank=True, null=True, verbose_name='المحتوى المبسط'),
        ),
    ]
