# Generated by Django 5.1.6 on 2026-04-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0025_lessoncontent_simplified_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='student',
            name='directorate',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
