# Generated by Django 5.1.6 on 2026-04-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0026_student_area_student_directorate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
