# Generated by Django 5.1.6 on 2026-04-12 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0027_remove_student_area_student_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningsession',
            name='is_watched',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='LessonWatchRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_records', to='learning.lessoncontent')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_records', to='learning.student')),
            ],
            options={
                'unique_together': {('student', 'lesson')},
            },
        ),
    ]
