# Generated by Django 5.1.6 on 2026-04-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0028_learningsession_is_watched_lessonwatchrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessoncontent',
            name='content_updated_at',
            field=models.DateTimeField(blank=True, db_column='ContentUpdatedAt', null=True),
        ),
    ]
