# Generated by Django 5.1.6 on 2026-04-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0029_lessoncontent_content_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userrole',
            field=models.CharField(blank=True, choices=[('', 'نوع المستخدم'), ('Admin', 'مشرف تقني'), ('SysAdmin', 'مشرف إداري'), ('Student', 'طالب'), ('Teacher', 'معلم'), ('Parent', 'ولي أمر')], db_column='UserRole', max_length=50, null=True),
        ),
    ]
