# Generated by Django 5.1.6 on 2026-04-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0030_alter_user_userrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='daily_lesson_limit',
            field=models.IntegerField(db_column='DailyLessonLimit', default=15),
        ),
    ]
