# Generated by Django 5.1.6 on 2026-04-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0031_alter_teacher_daily_lesson_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='school_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم المدرسة'),
        ),
    ]
