# Generated by Django 5.1.6 on 2026-04-20 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0032_student_school_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='lessonid',
            field=models.ForeignKey(blank=True, db_column='LessonID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.lessoncontent'),
        ),
    ]
