# Generated by Django 5.1.6 on 2026-04-20 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0033_alter_test_lessonid'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='subjectid',
            field=models.ForeignKey(blank=True, db_column='SubjectID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.subject'),
        ),
    ]
