# Generated by Django 5.2.9 on 2026-05-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0037_studentcheckpointanswer_response_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpoint',
            name='display_type',
            field=models.CharField(choices=[('end_paragraph', 'نهاية الفقرة'), ('distraction', 'عند التشتت')], db_column='DisplayType', default='end_paragraph', help_text='وقت عرض السؤال: نهاية الفقرة أو عند التشتت', max_length=20),
        ),
    ]
