# Generated by Django 5.2.9 on 2026-05-22 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0038_checkpoint_display_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningState',
            fields=[
                ('stateid', models.AutoField(db_column='StateID', primary_key=True, serialize=False)),
                ('behavioral_engagement_score', models.FloatField(db_column='BehavioralEngagementScore', default=0.0, help_text='مؤشر الانخراط السلوكي (0-1) من تحليل حركة العين والرأس')),
                ('learning_state_probability', models.FloatField(db_column='LearningStateProbability', default=0.5, help_text='احتمالية حالة التعلم (0-1) - مؤشر شامل')),
                ('cognitive_connection_score', models.FloatField(db_column='CognitiveConnectionScore', default=0.5, help_text='مؤشر الاتصال المعرفي (0-1) من إجابات نقاط التحقق')),
                ('cognitive_load', models.CharField(choices=[('low', 'منخفض'), ('optimal', 'مثالي'), ('high', 'عالي'), ('overload', 'فائق')], db_column='CognitiveLoad', default='optimal', help_text='الحمل الإدراكي الحالي', max_length=20)),
                ('temporal_trend', models.CharField(choices=[('improving', 'محسّن'), ('stable', 'مستقر'), ('declining', 'تناقص'), ('fluctuating', 'متذبذب')], db_column='TemporalTrend', default='stable', help_text='الاتجاه الزمني لحالة التعلم', max_length=20)),
                ('time_window_start', models.DateTimeField(db_column='TimeWindowStart')),
                ('time_window_end', models.DateTimeField(db_column='TimeWindowEnd')),
                ('attention_samples_count', models.IntegerField(db_column='AttentionSamplesCount', default=0, help_text='عدد عينات الانتباه في هذه النافذة')),
                ('checkpoint_answers_count', models.IntegerField(db_column='CheckpointAnswersCount', default=0, help_text='عدد إجابات نقاط التحقق في هذه النافذة')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
            ],
            options={
                'db_table': 'LearningState',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LearningStateSnapshot',
            fields=[
                ('snapshotid', models.AutoField(db_column='SnapshotID', primary_key=True, serialize=False)),
                ('current_attention_score', models.FloatField(db_column='CurrentAttentionScore', default=0.0, help_text='درجة الانتباه الحالية (0-100)')),
                ('current_learning_state', models.FloatField(db_column='CurrentLearningState', default=0.5, help_text='حالة التعلم الحالية (0-1)')),
                ('head_yaw', models.FloatField(blank=True, db_column='HeadYaw', help_text='زاوية التفات الرأس', null=True)),
                ('head_pitch', models.FloatField(blank=True, db_column='HeadPitch', help_text='زاوية النظر للأعلى/الأسفل', null=True)),
                ('head_roll', models.FloatField(blank=True, db_column='HeadRoll', help_text='زاوية الإمالة', null=True)),
                ('gaze_horizontal', models.FloatField(blank=True, db_column='GazeHorizontal', help_text='زاوية النظر الأفقية', null=True)),
                ('gaze_vertical', models.FloatField(blank=True, db_column='GazeVertical', help_text='زاوية النظر العمودية', null=True)),
                ('is_looking_away', models.BooleanField(db_column='IsLookingAway', default=False, help_text='هل ينظر بعيداً؟')),
                ('ear_value', models.FloatField(blank=True, db_column='EARValue', help_text='قيمة EAR', null=True)),
                ('is_drowsy', models.BooleanField(db_column='IsDrowsy', default=False, help_text='هل يظهر نعاس؟')),
                ('snapshot_time', models.DateTimeField(auto_now_add=True, db_column='SnapshotTime')),
            ],
            options={
                'db_table': 'LearningStateSnapshot',
                'ordering': ['-snapshot_time'],
                'managed': True,
            },
        ),
        migrations.RemoveIndex(
            model_name='checkpoint',
            name='idx_chk_lesson_para',
        ),
        migrations.AlterUniqueTogether(
            name='checkpoint',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='studentcheckpointanswer',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='checkpoint_type',
            field=models.CharField(choices=[('mandatory', 'إجباري - دوري'), ('adaptive', 'تكيفي - عند انخفاض الانخراط')], db_column='CheckpointType', default='mandatory', help_text='نوع نقطة التحقق: إجباري (دوري) أو تكيفي (عند انخفاض الانخراط)', max_length=20),
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='content_type',
            field=models.CharField(choices=[('text', 'نص'), ('audio', 'صوت'), ('video', 'فيديو')], db_column='ContentType', default='text', help_text='نوع المحتوى المرتبط بنقطة التحقق', max_length=10),
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='engagement_threshold',
            field=models.FloatField(db_column='EngagementThreshold', default=0.5, help_text='عتبة الانخراط (0-1) لإظهار السؤال التكيفي'),
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='mandatory_frequency',
            field=models.IntegerField(db_column='MandatoryFrequency', default=20, help_text='نسبة الأسئلة الإجبارية (مثلاً: 20 تعني سؤال إجباري كل 20% من المحتوى)'),
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='option_c',
            field=models.CharField(blank=True, db_column='OptionC', help_text='الخيار الثالث (اختياري)', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='option_d',
            field=models.CharField(blank=True, db_column='OptionD', help_text='الخيار الرابع (اختياري)', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='video_timestamp',
            field=models.FloatField(blank=True, db_column='VideoTimestamp', help_text='الوقت بالثواني في الفيديو - للفيديو فقط', null=True),
        ),
        migrations.AddField(
            model_name='studentcheckpointanswer',
            name='cognitive_connection_state',
            field=models.CharField(choices=[('strong', 'قوي - استمرارية الفهم'), ('weak', 'ضعيف مؤقت'), ('disconnected', 'منقطع')], db_column='CognitiveConnectionState', default='strong', help_text='حالة الاتصال المعرفي بناءً على الإجابة', max_length=20),
        ),
        migrations.AddField(
            model_name='studentcheckpointanswer',
            name='current_paragraph_index',
            field=models.IntegerField(blank=True, db_column='CurrentParagraphIndex', help_text='رقم الفقرة الحالية عند الإجابة', null=True),
        ),
        migrations.AddField(
            model_name='studentcheckpointanswer',
            name='current_video_position',
            field=models.FloatField(blank=True, db_column='CurrentVideoPosition', help_text='موضع الفيديو الحالي بالثواني عند الإجابة', null=True),
        ),
        migrations.AddField(
            model_name='studentcheckpointanswer',
            name='is_correct',
            field=models.BooleanField(db_column='IsCorrect', default=False, help_text='هل الإجابة صحيحة؟ (داخلي فقط - لا يُعرض للطالب)'),
        ),
        migrations.AddField(
            model_name='studentcheckpointanswer',
            name='support_intervention_triggered',
            field=models.BooleanField(db_column='SupportInterventionTriggered', default=False, help_text='هل تم تفعيل الرجوع 5 ثواني لإعادة بناء السياق؟'),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='correct_answer',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], db_column='CorrectAnswer', help_text='الإجابة الصحيحة (للمعلم فقط)', max_length=10),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='paragraph_index',
            field=models.IntegerField(blank=True, db_column='ParagraphIndex', help_text='رقم الفقرة (يبدأ من 0) - للنص فقط', null=True),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='question',
            field=models.CharField(db_column='Question', help_text='سؤال قصير', max_length=500),
        ),
        migrations.AlterField(
            model_name='studentcheckpointanswer',
            name='selected_answer',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], db_column='SelectedAnswer', help_text='الإجابة التي اختارها الطالب', max_length=10),
        ),
        migrations.AddIndex(
            model_name='checkpoint',
            index=models.Index(fields=['lessonid', 'checkpoint_type'], name='idx_chk_lesson_type'),
        ),
        migrations.AddIndex(
            model_name='checkpoint',
            index=models.Index(fields=['video_timestamp'], name='idx_chk_timestamp'),
        ),
        migrations.AddIndex(
            model_name='studentcheckpointanswer',
            index=models.Index(fields=['answered_at'], name='idx_chk_ans_time'),
        ),
        migrations.AddField(
            model_name='learningstate',
            name='sessionid',
            field=models.ForeignKey(db_column='SessionID', on_delete=django.db.models.deletion.CASCADE, to='learning.learningsession'),
        ),
        migrations.AddField(
            model_name='learningstate',
            name='studentid',
            field=models.ForeignKey(db_column='StudentID', on_delete=django.db.models.deletion.CASCADE, to='learning.student'),
        ),
        migrations.AddField(
            model_name='learningstatesnapshot',
            name='sessionid',
            field=models.ForeignKey(db_column='SessionID', on_delete=django.db.models.deletion.CASCADE, to='learning.learningsession'),
        ),
        migrations.AddField(
            model_name='learningstatesnapshot',
            name='studentid',
            field=models.ForeignKey(db_column='StudentID', on_delete=django.db.models.deletion.CASCADE, to='learning.student'),
        ),
        migrations.RemoveField(
            model_name='checkpoint',
            name='display_type',
        ),
        migrations.AddIndex(
            model_name='learningstate',
            index=models.Index(fields=['sessionid'], name='idx_ls_session'),
        ),
        migrations.AddIndex(
            model_name='learningstate',
            index=models.Index(fields=['studentid'], name='idx_ls_student'),
        ),
        migrations.AddIndex(
            model_name='learningstate',
            index=models.Index(fields=['time_window_start'], name='idx_ls_time_start'),
        ),
        migrations.AddIndex(
            model_name='learningstate',
            index=models.Index(fields=['sessionid', '-created_at'], name='idx_ls_session_time'),
        ),
        migrations.AddIndex(
            model_name='learningstatesnapshot',
            index=models.Index(fields=['sessionid'], name='idx_lss_session'),
        ),
        migrations.AddIndex(
            model_name='learningstatesnapshot',
            index=models.Index(fields=['studentid'], name='idx_lss_student'),
        ),
        migrations.AddIndex(
            model_name='learningstatesnapshot',
            index=models.Index(fields=['snapshot_time'], name='idx_lss_time'),
        ),
        migrations.AddIndex(
            model_name='learningstatesnapshot',
            index=models.Index(fields=['sessionid', '-snapshot_time'], name='idx_lss_session_time'),
        ),
    ]
