# Generated by Django 5.2.9 on 2026-05-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0039_learningstate_learningstatesnapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpoint',
            name='display_type',
            field=models.CharField(choices=[('scheduled', 'مجدول - يظهر في الوقت المحدد فقط'), ('distraction', 'عند التشتت - يظهر فقط عند رصد التشتت'), ('both', 'كلاهما - يظهر في الوقت المحدد وعند التشتت')], db_column='DisplayType', default='scheduled', help_text='نوع العرض: مجدول (في الوقت المحدد فقط)، عند التشتت (فقط عند رصد التشتت)، أو كلاهما', max_length=20),
        ),
    ]
