# Generated by Django 5.2.9 on 2026-05-31 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0040_checkpoint_display_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTeacherAssignment',
            fields=[
                ('assignmentid', models.AutoField(db_column='AssignmentID', primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('classid', models.ForeignKey(blank=True, db_column='ClassID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.class')),
                ('studentid', models.ForeignKey(db_column='StudentID', on_delete=django.db.models.deletion.CASCADE, to='learning.student')),
                ('subjectid', models.ForeignKey(blank=True, db_column='SubjectID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.subject')),
                ('teacherid', models.ForeignKey(db_column='TeacherID', on_delete=django.db.models.deletion.CASCADE, to='learning.teacher')),
            ],
            options={
                'db_table': 'StudentTeacherAssignment',
                'managed': True,
                'unique_together': {('studentid', 'teacherid', 'subjectid')},
            },
        ),
    ]
