# Generated by Django 5.2.9 on 2026-05-31 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0041_studentteacherassignment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentteacherassignment',
            unique_together={('studentid', 'teacherid')},
        ),
        migrations.RemoveField(
            model_name='studentteacherassignment',
            name='classid',
        ),
        migrations.RemoveField(
            model_name='studentteacherassignment',
            name='subjectid',
        ),
    ]
