# Generated by Django 5.2.9 on 2026-05-31 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0042_alter_studentteacherassignment_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentteacherassignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='studentteacherassignment',
            name='classid',
            field=models.ForeignKey(blank=True, db_column='ClassID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.class'),
        ),
        migrations.AddField(
            model_name='studentteacherassignment',
            name='subjectid',
            field=models.ForeignKey(blank=True, db_column='SubjectID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='studentteacherassignment',
            unique_together={('studentid', 'teacherid', 'subjectid')},
        ),
    ]
