# Generated by Django 5.2.9 on 2026-05-23 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BehavioralBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calibration_sessions_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('ear_mean', models.FloatField(blank=True, null=True)),
                ('ear_std', models.FloatField(blank=True, null=True)),
                ('ear_min', models.FloatField(blank=True, null=True)),
                ('ear_max', models.FloatField(blank=True, null=True)),
                ('head_yaw_mean', models.FloatField(blank=True, null=True)),
                ('head_yaw_std', models.FloatField(blank=True, null=True)),
                ('head_pitch_mean', models.FloatField(blank=True, null=True)),
                ('head_pitch_std', models.FloatField(blank=True, null=True)),
                ('head_roll_mean', models.FloatField(blank=True, null=True)),
                ('head_roll_std', models.FloatField(blank=True, null=True)),
                ('gaze_horizontal_mean', models.FloatField(blank=True, null=True)),
                ('gaze_horizontal_std', models.FloatField(blank=True, null=True)),
                ('gaze_vertical_mean', models.FloatField(blank=True, null=True)),
                ('gaze_vertical_std', models.FloatField(blank=True, null=True)),
                ('nose_ear_ratio_mean', models.FloatField(blank=True, null=True)),
                ('nose_ear_ratio_std', models.FloatField(blank=True, null=True)),
                ('head_turn_frequency', models.FloatField(blank=True, null=True)),
                ('gaze_away_frequency', models.FloatField(blank=True, null=True)),
                ('drowsy_frequency', models.FloatField(blank=True, null=True)),
                ('ear_threshold_personal', models.FloatField(blank=True, null=True)),
                ('yaw_threshold_personal', models.FloatField(blank=True, null=True)),
                ('pitch_threshold_personal', models.FloatField(blank=True, null=True)),
                ('roll_threshold_personal', models.FloatField(blank=True, null=True)),
                ('gaze_horizontal_threshold_personal', models.FloatField(blank=True, null=True)),
                ('gaze_vertical_threshold_personal', models.FloatField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('calibration_completed_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='behavioral_baseline', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'النموذج السلوكي الشخصي',
                'verbose_name_plural': 'النماذج السلوكية الشخصية',
            },
        ),
        migrations.CreateModel(
            name='CalibrationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_number', models.IntegerField(default=1)),
                ('duration_minutes', models.IntegerField(default=3)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('time_of_day', models.CharField(blank=True, choices=[('morning', 'صباحاً'), ('afternoon', 'ظهراً'), ('evening', 'مساءً'), ('night', 'ليلاً')], max_length=20)),
                ('environment_notes', models.TextField(blank=True)),
                ('behavioral_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibration_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'جلسة معايرة',
                'verbose_name_plural': 'جلسات المعايرة',
                'ordering': ['-start_time'],
            },
        ),
    ]
