# Generated by Django 5.2.9 on 2026-05-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationsession',
            name='custom_content',
            field=models.TextField(blank=True, help_text='محتوى مخصص للعرض أثناء جلسة المعايرة'),
        ),
    ]
