# Generated by Django 5.2.9 on 2026-05-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_calibrationsession_custom_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calibrationsession',
            name='custom_content',
        ),
        migrations.AddField(
            model_name='calibrationsession',
            name='calibration_video',
            field=models.FileField(blank=True, help_text='فيديو مخصص للعرض أثناء جلسة المعايرة (حتى 5 دقائق)', null=True, upload_to='calibration_videos/'),
        ),
    ]
