# Generated by Django 5.2.9 on 2026-05-30 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0003_remove_calibrationsession_custom_content_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='behavioralbaseline',
            name='ear_mad',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='behavioralbaseline',
            name='ear_median',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='behavioralbaseline',
            name='gaze_horizontal_mad',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='behavioralbaseline',
            name='gaze_horizontal_median',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='behavioralbaseline',
            name='gaze_vertical_mad',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='behavioralbaseline',
            name='gaze_vertical_median',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='behavioralbaseline',
            name='head_pitch_mad',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='behavioralbaseline',
            name='head_pitch_median',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='behavioralbaseline',
            name='head_roll_mad',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='behavioralbaseline',
            name='head_roll_median',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='behavioralbaseline',
            name='head_yaw_mad',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='behavioralbaseline',
            name='head_yaw_median',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CPTLSBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gaze_mean', models.FloatField(default=0.0)),
                ('head_mean', models.FloatField(default=0.0)),
                ('ear_mean', models.FloatField(default=0.0)),
                ('response_mean', models.FloatField(default=0.0)),
                ('gaze_std', models.FloatField(default=1.0)),
                ('head_std', models.FloatField(default=1.0)),
                ('ear_std', models.FloatField(default=1.0)),
                ('response_std', models.FloatField(default=1.0)),
                ('calibration_samples', models.IntegerField(default=0)),
                ('calibration_sessions_count', models.IntegerField(default=0)),
                ('gaze_weight', models.FloatField(default=0.3)),
                ('head_weight', models.FloatField(default=0.25)),
                ('ear_weight', models.FloatField(default=0.25)),
                ('response_weight', models.FloatField(default=0.2)),
                ('alpha', models.FloatField(default=0.85)),
                ('is_active', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('calibration_completed_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cptls_baseline', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CPTLS Baseline',
                'verbose_name_plural': 'CPTLS Baselines',
            },
        ),
        migrations.CreateModel(
            name='CPTLSCalibrationSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gaze', models.FloatField()),
                ('head', models.FloatField()),
                ('ear', models.FloatField()),
                ('response', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('calibration_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cptls_samples', to='student_app.calibrationsession')),
            ],
            options={
                'verbose_name': 'CPTLS Calibration Sample',
                'verbose_name_plural': 'CPTLS Calibration Samples',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CPTLSSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_id', models.IntegerField(blank=True, null=True)),
                ('session_type', models.CharField(choices=[('lesson', 'درس'), ('video', 'فيديو'), ('practice', 'تدريب'), ('test', 'اختبار')], default='lesson', max_length=20)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('total_samples', models.IntegerField(default=0)),
                ('average_engagement', models.FloatField(blank=True, null=True)),
                ('final_temporal_state', models.FloatField(blank=True, null=True)),
                ('sustained_distraction_detected', models.BooleanField(default=False)),
                ('distraction_episodes_count', models.IntegerField(default=0)),
                ('risk_level', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cptls_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CPTLS Session',
                'verbose_name_plural': 'CPTLS Sessions',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='CPTLSStateSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('gaze_raw', models.FloatField()),
                ('head_raw', models.FloatField()),
                ('ear_raw', models.FloatField()),
                ('response_raw', models.FloatField()),
                ('gaze_normalized', models.FloatField()),
                ('head_normalized', models.FloatField()),
                ('ear_normalized', models.FloatField()),
                ('response_normalized', models.FloatField()),
                ('gaze_probability', models.FloatField()),
                ('head_probability', models.FloatField()),
                ('ear_probability', models.FloatField()),
                ('response_probability', models.FloatField()),
                ('fused_probability', models.FloatField()),
                ('temporal_state', models.FloatField()),
                ('engagement_percentage', models.FloatField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_snapshots', to='student_app.cptlssession')),
            ],
            options={
                'verbose_name': 'CPTLS State Snapshot',
                'verbose_name_plural': 'CPTLS State Snapshots',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['session', 'timestamp'], name='student_app_session_4c3489_idx')],
            },
        ),
    ]
