# Generated by Django 5.2.9 on 2026-05-31 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0004_behavioralbaseline_ear_mad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='behavioralbaseline',
            name='blink_rate_mad',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='behavioralbaseline',
            name='blink_rate_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='behavioralbaseline',
            name='blink_rate_median',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='behavioralbaseline',
            name='blink_rate_std',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='behavioralbaseline',
            name='blink_rate_weight',
            field=models.FloatField(default=0.2),
        ),
        migrations.AddField(
            model_name='behavioralbaseline',
            name='checkpoint_fail_weight',
            field=models.FloatField(default=0.15),
        ),
        migrations.AddField(
            model_name='behavioralbaseline',
            name='ear_threshold_k',
            field=models.FloatField(default=2.0),
        ),
        migrations.AddField(
            model_name='behavioralbaseline',
            name='eye_gaze_weight',
            field=models.FloatField(default=0.3),
        ),
        migrations.AddField(
            model_name='behavioralbaseline',
            name='head_pose_weight',
            field=models.FloatField(default=0.25),
        ),
        migrations.AddField(
            model_name='behavioralbaseline',
            name='interaction_weight',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='behavioralbaseline',
            name='level1_probability_threshold',
            field=models.FloatField(default=0.3),
        ),
        migrations.AddField(
            model_name='behavioralbaseline',
            name='level2_probability_threshold',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='behavioralbaseline',
            name='level3_probability_threshold',
            field=models.FloatField(default=0.7),
        ),
        migrations.AddField(
            model_name='behavioralbaseline',
            name='temporal_smoothing_alpha',
            field=models.FloatField(default=0.85),
        ),
    ]
